//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootwearShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootwearShopEntities : DbContext
    {
        public FootwearShopEntities()
            : base("name=FootwearShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Footwear> Footwears { get; set; }
        public virtual DbSet<FootwearType> FootwearTypes { get; set; }
        public virtual DbSet<Maker> Makers { get; set; }
        public virtual DbSet<Motion> Motions { get; set; }
    }
}
