//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootwearShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footwear
    {
        public Footwear()
        {
            this.Motions = new HashSet<Motion>();
        }
    
        public int Id { get; set; }
        public int MakerId { get; set; }
        public int TypeId { get; set; }
        public int FootwearSize { get; set; }
        public double Price { get; set; }
    
        public virtual Maker Maker { get; set; }
        public virtual FootwearType FootwearType { get; set; }
        public virtual ICollection<Motion> Motions { get; set; }
    }
}
