//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootwearShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motion
    {
        public int Id { get; set; }
        public int FootwearId { get; set; }
        public int Amount { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Footwear Footwear { get; set; }
    }
}
